default: &default
  adapter: postgresql
  encoding: utf8
  pool: 10
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: mp3downloadr_production
